-- Add intervene flag to pair_session
ALTER TABLE pair_session ADD COLUMN intervene BOOLEAN NOT NULL DEFAULT FALSE;

-- Stores instructions generated by the pair agent to be injected into the
-- worker agent's next task prompt on the same issue.
CREATE TABLE pair_intervention (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id  UUID NOT NULL REFERENCES pair_session(id) ON DELETE CASCADE,
    issue_id    UUID NOT NULL,
    content     TEXT NOT NULL,
    consumed    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX pair_intervention_issue_unconsumed ON pair_intervention (issue_id) WHERE consumed = FALSE;